name: phagepickr
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.11
  - biopython=1.83
  - numpy=1.26.0
  - pandas=2.1.1
  - scikit-learn=1.2.2
  - scipy=1.13.1
  - mafft
  - pip=24.0
  - pip:
    - -e . 